### ISSUE TITLE
pan-epitope-model

### ISSUE THREAD

**Issue by ShadoWyyyy** [GfellerLab/MixTCRpred#2]
Hi, brilliant work, I am wondering do users have access to pan-epitope-model for prediction of previous unseen allele-peptide-tcr binding prediction, do I miss the option or just not available yet, hope for response

**Comment by GiancarloCroce** [comment]
Hi, 
Thanks for your interest in our work. Currently, access to a pan-epitope model is not available. The pan-epitope model that we investigated in the paper  (https://www.nature.com/articles/s41467-024-47461-8) is the "TransformerPredictor_AB_cdr123_with_epi" in the ./src/model.py file, but this is not supported by the MixTCRpred version on GitHub.

In the paper (Figure 3), we observed that extending predictions to unseen epitopes is challenging with the current amount of data. Successful predictions are possible only when the unseen epitope has very high sequence similarity with at least one epitope in the training set.

Best,
Giancarlo

**Comment by ShadoWyyyy** [comment]
> Hi, Thanks for your interest in our work. Currently, access to a pan-epitope model is not available. The pan-epitope model that we investigated in the paper (https://www.nature.com/articles/s41467-024-47461-8) is the "TransformerPredictor_AB_cdr123_with_epi" in the ./src/model.py file, but this is not supported by the MixTCRpred version on GitHub.
> 
> In the paper (Figure 3), we observed that extending predictions to unseen epitopes is challenging with the current amount of data. Successful predictions are possible only when the unseen epitope has very high sequence similarity with at least one epitope in the training set.
> 
> Best, Giancarlo

oh, I know, thanks for replying
