### ISSUE TITLE
Inquiry Regarding MixTCRpred to Streamlit Share

### ISSUE THREAD

**Issue by bitcometz** [GfellerLab/MixTCRpred#3]
Dear MixTCRpred developers,

I wanted to express my gratitude for developing such an excellent tool. MixTCRpred has greatly facilitated my studies.

Recently, I've been considering deploying this software to Streamlit Share to share it with a wider audience. However, I want to ensure that you have no objections to this. Therefore, I'm reaching out to seek your opinion and permission.

https://share.streamlit.io/

Best

**Comment by GiancarloCroce** [comment]
Hi,

Thank you for your interest in our work! It's theoretically possible, but there are some licensing matters that need to be discussed. Could you please reach out to us via email (Giancarlo Croce and David Gfeller)? You can find our email addresses on the GitHub README.

Thank you!

Best,
Giancarlo

**Comment by bitcometz** [comment]
thanks
