### ISSUE TITLE
prediction performance without peptide sequence

### ISSUE THREAD

**Issue by Sophon-0** [GfellerLab/MixTCRpred#5]
Hello, 
I was trying to reproduce the result of the paper following as much as possible the different steps and my results are very similar to the paper, using my own method. One thing that is surprising to me is that when i remove the peptide sequence info (epitope and CDR3) and only use HLA and VJ genes info, the performance is much better. I wonder if you benchmarked the performance of peptide info versus  the genes info as input features. 
Thanks !

**Comment by GiancarloCroce** [comment]
Hi,
Thank you for your interest in our work! It is great you were able to reproduce our results.
MixTCRpred is an epitope-specific model, meaning a separate model is trained for each epitope (a peptide presented by a specific HLA). The training data consists of CDR1, CDR2, and CDR3 sequences of epitope-specific TCRs. 

We did not explore using the HLA and VJ genes as input features, so I am not be able to comment further on that aspect.
Best wishes for your research endeavors,

Best,
Giancarlo
